### ISSUE TITLE
One or more packages are incompatible with .NETCoreApp,Version=v1.0.

### ISSUE THREAD

**Issue by uglyfatbald** [oelite/RESTme#15]
Trying to test this library I create a simple application using "Console Application (.Net Core)" template in Visual Studio 2015.

Execute: Install-Package OElite.Restme from Package Manager Console, and I get:

Errors in C:\Users\Administrator\Documents\Visual Studio 2015\Projects\TestRestClientConsoleApp\src\TestRestClientConsoleApp\TestRestClientConsoleApp.xproj
    Package System.Spatial 5.6.4 is not compatible with netcoreapp1.0 (.NETCoreApp,Version=v1.0). Package System.Spatial 5.6.4 supports:
      - net40 (.NETFramework,Version=v4.0)
      - portable-net40+sl5+win8+wp8+wpa81 (.NETPortable,Version=v0.0,Profile=Profile328)
      - portable-net45+win8+wp8+wpa81 (.NETPortable,Version=v0.0,Profile=Profile259)
      - sl4 (Silverlight,Version=v4.0)
    Package Microsoft.Data.Services.Client 5.6.4 is not compatible with netcoreapp1.0 (.NETCoreApp,Version=v1.0). Package Microsoft.Data.Services.Client 5.6.4 supports:
      - net40 (.NETFramework,Version=v4.0)
      - portable-net45+win8+wp8+wpa81 (.NETPortable,Version=v0.0,Profile=Profile259)
      - sl4 (Silverlight,Version=v4.0)
    Package Microsoft.Data.OData 5.6.4 is not compatible with netcoreapp1.0 (.NETCoreApp,Version=v1.0). Package Microsoft.Data.OData 5.6.4 supports:
      - net40 (.NETFramework,Version=v4.0)
      - portable-net40+sl5+win8+wp8+wpa81 (.NETPortable,Version=v0.0,Profile=Profile328)
      - portable-net45+win8+wp8+wpa81 (.NETPortable,Version=v0.0,Profile=Profile259)
      - sl4 (Silverlight,Version=v4.0)
    Package Microsoft.Data.Edm 5.6.4 is not compatible with netcoreapp1.0 (.NETCoreApp,Version=v1.0). Package Microsoft.Data.Edm 5.6.4 supports:
      - net40 (.NETFramework,Version=v4.0)
      - portable-net40+sl5+win8+wp8+wpa81 (.NETPortable,Version=v0.0,Profile=Profile328)
      - portable-net45+win8+wp8+wpa81 (.NETPortable,Version=v0.0,Profile=Profile259)
      - sl4 (Silverlight,Version=v4.0)
    One or more packages are incompatible with .NETCoreApp,Version=v1.0.

**Comment by mleader1** [comment]
hi @uglyfatbald ,

try update your project.json . with the following:

`
"netcoreapp1.0": {
      "imports": [
        "dnxcore50",
        "netcore50",
        "portable-net451+win8"
      ]
    }
`

the third party packages that RESTme package depends on require additional library sources.

I'll commit a simple example to the repository when I get time

**Comment by mleader1** [comment]
added new ConsoleApp sample,  also made a new Nuget package release (minor updates to 1.0.7)

enjoy.

**Comment by uglyfatbald** [comment]
hi @mleader1 , thanks for your answer. This is my actual project.json:

```
{
  "version": "1.0.0-*",
  "buildOptions": {
    "emitEntryPoint": true
  },

  "dependencies": {
    "Microsoft.NETCore.App": {
      "type": "platform",
      "version": "1.0.0"
    },
    "OElite.Restme": "1.0.7"},

  "frameworks": {
    "netcoreapp1.0": {
      "imports": [ "dnxcore50", "netcore50", "portable-net451+win8"]
    }
  }
}
```

But I still have this error:

Errors in C:\Users\Administrator\Documents\Visual Studio 2015\Projects\TestRestClientConsoleApp\src\TestRestClientConsoleApp\TestRestClientConsoleApp.xproj
    Unable to resolve 'OElite.Restme.Utils (>= 1.0.1-dev-77)' for '.NETCoreApp,Version=v1.0'.

**Comment by mleader1** [comment]
hi @uglyfatbald  thanks for this - Have just made OElite.Restme.Utils released on Nuget so you should be able to run your application without issues now.

cheers.

**Comment by uglyfatbald** [comment]
Just tested and works!
Thanks a lot @mleader1
